### PR TITLE
Setting up GitPod

### PR DESCRIPTION
**Pull request by alaxalves**
Available at: https://fac31da2-a42d-4cdb-9c3b-c7c41682cda1.ws-us02.gitpod.io/#/workspace/spectral-workbench

Make sure these boxes are checked before your pull request is ready to be reviewed and merged. Thanks!

* [x] tests pass -- `rake test`
* [x] code is in uniquely-named feature branch, and has been rebased on top of latest master (especially if you've been asked to make additional changes)
* [x] pull request are descriptively named
* [ ] if possible, multiple commits squashed if they're smaller changes
* [ ] reviewed/confirmed/tested by another contributor or maintainer

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/wiki/contributing-to-public-lab-software

Thanks!

### CODE REVIEW

**Comment by alaxalves** [comment]
Working like a charm :)
image

**Review by cesswairimu — APPROVED** [review]
works really good. Fantastic job :rocket:

**Comment by jywarren** [comment]
Wow amazing!!!! Great work @alaxalves. Should we merge this before or after https://github.com/publiclab/spectral-workbench/pull/539 ?

**Comment by alaxalves** [comment]
Before please

**Pull request merged**
