### PR TITLE
System tests for `/capture` `/capture/v2` and `/upload`

### PR DESCRIPTION
**Pull request by waridrox**
Implementing tests for /capture/v2 | /capture | /upload

Allowing camera access(not working)- https://webrtc.github.io/webrtc-org/testing/

https://user-images.githubusercontent.com/58583793/130129346-64b3c580-40e2-4e1d-9a06-158caa636f34.mov

* [ ] tests pass -- `rake test`
* [ ] code is in uniquely-named feature branch, and has been rebased on top of latest master (especially if you've been asked to make additional changes)
* [ ] pull request are descriptively named
* [ ] if possible, multiple commits squashed if they're smaller changes
* [ ] reviewed/confirmed/tested by another contributor or maintainer

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/wiki/contributing-to-public-lab-software

Thanks!

### CODE REVIEW

**Comment by waridrox** [comment]
Hi @jywarren, I'm not able to get the fake camera feed work 😕 by passing in the arguments: `--use-fake-device-for-media-stream` and `--use-fake-ui-for-media-stream` in the Selenium Chrome driver. Other than that I've created tests for `/upload`, `/capture` and `/capture/v2` routes which capture the spectrum and delete it after logging in with a random username using the `faker` gem.

More on this at - 

- https://webrtc.github.io/webrtc-org/testing/
- https://elh.mx/generales/testing-webrtc-fake-camera-with-cucumbercapybara-in-chrome/

**Comment by jywarren** [comment]
Ah hm... Shall we merge the tests that do work and open a new issue or PR with the ones that don't?

**Comment by jywarren** [comment]
These look fantastic though. Great work!

**Comment by waridrox** [comment]
The only thing that is missing is the fake video stream, which could check for live graphs to make the tests more comprehensive. Otherwise these are good to go for crucial things like creating and deleting a spectrum...

**Comment by waridrox** [comment]
There was a dependency update since I'm using the `faker` gem. Not sure how this will affect the overall app in production...

**Comment by waridrox** [comment]
Reverted the dependencies to original, @jywarren pls take a look. Thanks

**Comment by jywarren** [comment]
Great work!!

**Pull request merged**
