### PR TITLE
Routes re-factoring and cleaning

### PR DESCRIPTION
**Pull request by vpowerrc**
This is not yet ready for merging; just posting to stay coordinated. 

Signed-off-by: Viduranga Wijesooriya <vpowerrc@gmail.com>

### CODE REVIEW

**Comment by jywarren** [comment]
Hi, Viduranga - I see you're removing whitespace from files like `app/views/layouts/application.html.erb` -- I'm editing those files too, actually. It won't cause a big problem, but it'd be nice if you generally stuck to the files your key changes will be in, to try to avoid conflicts. Although if you say "I'm going to go in and reformat tabbing and whitespace across all files" then everyone else can coordinate around such a large widespread change. 

Anyhow, looks good! If you have any chance to write tests for your new code that'd be great too. Once I got tests running in MapKnitter, I felt much more comfortable doing big refactorings, since it was much easier to be sure major functions were still working.

**Comment by vpowerrc** [comment]
Actually application.html contains a change other than the white space removals. 
Thing is my text editor automatically removes white spaces whenever I edited a file. 
So shall I avoid it?
Sure, I will write some tests too.

**Comment by jywarren** [comment]
No, it's ok. That kind of thing is pretty easy to resolve with git rebase.
Thanks!

**Comment by jywarren** [comment]
@vpowerrc -- my asset pipeline work in #86 turned out to be more complex than I'd thought because we have some offline manifest caching in /capture ([you can read more about offline manifests here](http://www.html5rocks.com/en/tutorials/appcache/beginner/))

And, it may actually overlap with the routes work you're doing because the best way to get the offline manifest to work with the asset pipeline is to use the "rack-offline" gem, which is initialized in the `routes.rb` file. Sorry, this is a pain. How close are you on your routes changes, or could you find a stopping point so I can pull in your changes and add my own routes.rb work on top of it? I just don't want to get too crazy.

On the other hand, I'll only be adding a couple lines to routes.rb, so it may not be a big deal if we both edit that file. But if there's a place you can stop for a day, that could be cleaner for us both.

**Comment by vpowerrc** [comment]
Okay. I will hold it for a day. Let me know when you are finished.

**Comment by jywarren** [comment]
Ok, are all your changes so far done and are added to the PR?

**Comment by vpowerrc** [comment]
yes

**Comment by jywarren** [comment]
Hi, Viduranga -- why don't you go ahead - my only worry was that I'd finish before you, but that doesn't seem likely at this point. 

If I finish first, that's not a problem; I'll rebase. If you finish first, I can help you rebase on top of my changes if need be. 

So in any case thank you for your patience, and keep going!

My task is ending up being quite a bit harder than I thought -- getting offline files working at the same time as the asset pipeline.

**Comment by jywarren** [comment]
Hmm, made a little more progress. If you'd like to try it out, see this branch: https://github.com/publiclab/spectral-workbench/pull/86

**Comment by jywarren** [comment]
OK, I think I'm done. Viduranga, shall I pull in what you have so far, or are you comfortable following the guidelines for rebasing at http://publiclab.org/wiki/contributing-to-public-lab-software ?

**Comment by vpowerrc** [comment]
Jeff,
Great. Do you want me to rebase with your branch? I'm more familiar with merge rather than rebase, but nevertheless I can follow the guideline.

**Comment by btbonval** [comment]
@vpowerrc as a high level explanation: rebase is like a merge, but instead of two branches coming together at the merge commit, rebase takes one branch and runs its commits linearly at the end of another branch.

rebase makes for more linear merges later and reduces the number of commits in the tree devoted to merges. The cost is that rebase can change history (if it is used in an existing branch) and it duplicates the commits of the branch being rebased. If the history is changed, you have to be careful with pull and push. Specifically, don't push a branch until after rebase has been run for the last time ;)

It is a tradeoff. The current common practice is to rebase upstream branches into feature branches, and merge feature branches into upstream branches.

**Comment by vpowerrc** [comment]
@btbonval 
Thank you for explaining. I manged to do the rebase

@jywarren 
There were couple of conflicts. I managed to fix them. 
But now some assets are not loading. I think their paths are wrong. Are you aware of this issue?
I can't run the application now. It gives errors. Shall I try to fix them?

**Comment by vpowerrc** [comment]
@btbonval 
This same thing happened to me after the rebase. 
http://stackoverflow.com/questions/8939977/git-push-rejected-after-feature-branch-rebase

What do you think I should do?

**Comment by jywarren** [comment]
Hi, Viduranga - can you post a Gist of the errors? Did you rebase on top of
my asset pipeline work? In what branch so I can see?

**Comment by vpowerrc** [comment]
Yes on top of your asset-pipeline branch.

ActionView::Template::Error (couldn't find file 'bootstrap-css/css/bootstrap.min.css'
  (in /home/viduranga/Desktop/gsoc/publiclab/spectral-workbench/app/assets/stylesheets/application.css:11)):

app/views/layouts/application.html.erb:17:in `_app_views_layouts_application_html_erb___3070997007425473229_70181786122340'

ActionController::RoutingError (No route matches [GET] "/lib/fontawesome/css/font-awesome.min.css"):

ActionController::RoutingError (No route matches [GET] "/lib/junction/webfonts/junction-regular.eot"):

**Comment by jywarren** [comment]
Ah, you have to install bower and run `bower install` from the root
directory; you can follow some of the steps starting at "install bower"
here: https://github.com/publiclab/mapknitter/#prerequisites

The process is the same otherwise.

**Comment by vpowerrc** [comment]
Oh, I thought we are going to remove it when moving with the asset pipeline. My bad

BTW do you have any idea what to do for 
http://stackoverflow.com/questions/8939977/git-push-rejected-after-feature-branch-rebase

There are 2 options
1. Force push
2.  After the rebase, merge in the old head of feature with -s ours

**Comment by btbonval** [comment]
You shouldn't force push unless you know what you are doing.

Basically this means the branch you are on had already been pushed, you've
changed the commit history with a rebase, and now the upstream branch
history doesn't blend.

Generally I create a new branch of the rebased branch. The new branch won't
have an existing history on the upstream, and it can be pushed.

**Comment by btbonval** [comment]
I sometimes have three branches, reach a branch off another branch, while
working. Only the most recently branch matters, the others are like save
points or bookmarks.

When the feature is complete, I merge into master and delete the branches I
had been using.

**Comment by btbonval** [comment]
Sorry I am typing on my phone. I will edit my comments more sensibly when I
am at a computer.

**Comment by vpowerrc** [comment]
So I will delete this branch and create a new branch with the same name because I'm still working on routes. 
Is that good? or I can create a branch something like "routes-2"

**Comment by btbonval** [comment]
Don't delete anything. Just go with routes-2

**Comment by vpowerrc** [comment]
Okay, thanks

**Comment by jywarren** [comment]
Thanks all! Merged.

**Pull request closed without merging**
