### PR TITLE
revised JSON api and tests

### PR DESCRIPTION
**Pull request by jywarren**
* [ ] tests pass -- `rake test`
* [x] code is in uniquely-named feature branch, and has been rebased on top of latest master (especially if you've been asked to make additional changes)
* [x] pull request are descriptively named
* [x] if possible, multiple commits squashed if they're smaller changes
* [x] reviewed/confirmed/tested by another contributor or maintainer

### CODE REVIEW

**Comment by jywarren** [comment]
This is an odd one, @icarito, any ideas? It says it can find the right version of passenger:

````
Step 17 : RUN bundle exec rake db:setup

 ---> Running in f97f67c7d4e5

/usr/local/lib/ruby/gems/2.1.0/gems/bundler-1.7.3/lib/bundler/spec_set.rb:92:in `block in materialize': Could not find passenger-5.0.28 in any of the sources (Bundler::GemNotFound)

	from /usr/local/lib/ruby/gems/2.1.0/gems/bundler-1.7.3/lib/bundler/spec_set.rb:85:in `map!'
````

**Comment by jywarren** [comment]
Maybe it was dropped for security reasons and we can bump the version # for the next one?

**Comment by icarito** [comment]
It's strange but it looks similar to the issue we had with tzinfo - a new version of `passenger` was released yesterday and it's not being picked up because `Gemfile.lock` is requesting 5.0.28 but bundler is installing 5.0.29 for some reason. I'll research it more closely and come up with a solution.

**Comment by jywarren** [comment]
The Gemfile.lock does specify a given version # - in this case, 5.0.28. If they pulled 5.0.28 once 5.0.29 came out, that could fail.

**Comment by jywarren** [comment]
Perhaps the solution is for me to run `bundle update` to ensure the Gemfile.lock generated by my local system matches the available versions. Then the only way it'd error is if a new version is released between my `update` and the pull request's tests being run (and/or later, the production `bundle install`, of course).

**Comment by jywarren** [comment]
Trying an updated Gemfile.lock, plus some additional changes.

**Comment by jywarren** [comment]
Nice!

**Comment by icarito** [comment]
This issue was caused by #382

**Pull request merged**
