### PR TITLE
Add routes test for sets/find_match

### PR DESCRIPTION
**Pull request by dev-Suren**
Fixes #(update with issue number)

Make sure these boxes are checked before your pull request is ready to be reviewed and merged. Thanks!

* [ ] tests pass -- `rake test`
* [ ] code is in uniquely-named feature branch, and has been rebased on top of latest master (especially if you've been asked to make additional changes)
* [ ] pull request are descriptively named
* [ ] if possible, multiple commits squashed if they're smaller changes
* [ ] reviewed/confirmed/tested by another contributor or maintainer

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/wiki/contributing-to-public-lab-software

Thanks!

### CODE REVIEW

**Review by Tlazypanda — COMMENTED** [review]
Hey @dev-Suren it looks like you have made changes in the wrong file can you please make changes in the routes_test.rb file https://github.com/publiclab/spectral-workbench/blob/main/test/integration/routes_test.rb

**Review by Tlazypanda — COMMENTED** [review]
Hey @dev-Suren looks like the tests are failing. Can we make the following changes?  Rest all looks good :tada:  Thanks :v:

Before
`{"controller"=>"sets", "action"=>"find_match"}`

After
`{"controller"=>"sets", "action"=>"show", "id"=>"find_match"}`

**Review by TildaDares — APPROVED** [review]
Great work @dev-Suren. Thank you!

**Comment by TildaDares** [comment]
Congratulations and welcome to Public Lab @dev-Suren 🎉

**Pull request merged**
