### PR TITLE
Increase test coverage percentage

### PR DESCRIPTION
**Pull request by alaxalves**
Make sure these boxes are checked before your pull request is ready to be reviewed and merged. Thanks!

* [x] tests pass -- `rake test`
* [x] code is in uniquely-named feature branch, and has been rebased on top of latest master (especially if you've been asked to make additional changes)
* [ ] pull request are descriptively named
* [ ] if possible, multiple commits squashed if they're smaller changes
* [ ] reviewed/confirmed/tested by another contributor or maintainer

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/wiki/contributing-to-public-lab-software

Thanks!

### CODE REVIEW

**Comment by alaxalves** [comment]
Quoting https://github.com/publiclab/spectral-workbench/pull/513#issuecomment-642804471

**Comment by alaxalves** [comment]
The tests have passed according to https://travis-ci.org/github/publiclab/spectral-workbench/builds/697368735

**Comment by alaxalves** [comment]
@jywarren could you try the fix for this Travis + GH issue described at https://travis-ci.community/t/known-issue-travis-ci-reports-expected-waiting-for-status-to-be-reported-on-the-github-status-api-but-the-status-never-arrives/1154 ?? I do not have permission for that

**Comment by jywarren** [comment]
OK, found we have the old form here:

image

But you know, i think it's because this repo is still on `travis-ci.org` and not `.com`! We should probably switch as they gave up on `.org` a while back.

**Comment by jywarren** [comment]
See - https://travis-ci.org/github/publiclab/spectral-workbench.js not https://travis-ci.com/github/publiclab/spectral-workbench.js

it's because we were in the Open Source program (free) from early on, and they've changed how their plans are structured since.

**Comment by jywarren** [comment]
I think we have to do this -- maybe also for plots2... https://docs.travis-ci.com/user/migrate/open-source-repository-migration/

**Comment by jywarren** [comment]
Hmm, i don't seem to be able to view publiclab repositories, and can't add the organization...

image

**Comment by jywarren** [comment]
(from .org)

**Comment by jywarren** [comment]
Anyways once we migrate it we prob need to adjust these settings: https://github.com/publiclab/spectral-workbench/settings/branch_protection_rules/15230237

**Comment by jywarren** [comment]
ok seeing htis: https://travis-ci.community/t/suddenly-travis-ci-says-that-im-not-a-member-of-any-organization/5593

**Comment by jywarren** [comment]
Phew, this worked: https://travis-ci.community/t/travis-doesnt-report-back-and-all-organization-repos-are-gone/7772/5

**Comment by jywarren** [comment]
image

**Comment by jywarren** [comment]
OK! Started the migration! If this works, I'll migrate others too!

**Comment by jywarren** [comment]
Well, there seems to be a PR-based build queued now! Once it completes i think i can make it required here:

image

For the time being, i'll remove the requirement for the one marked `continuous-integration/travis-ci`. 

cc @icarito btw that we're trying to migrate travis-ci.org repos to travis-ci.com, with this as a first test!

**Comment by jywarren** [comment]
OK! It passed! And I removed the requirement for the old one, added requirement for the new check!

image

**Comment by jywarren** [comment]
Nice!!!! https://github.com/publiclab/spectral-workbench/runs/770364164

**Comment by alaxalves** [comment]
Thank you Jeff <3

**Pull request merged**
