### PR TITLE
dashboard.html.erb: Make sidebar consistent with the header

### LINKED ISSUE #443: Sidebar inconsistent with the header
image
I found after login we have username listed on the header but in the sidebar there is option for the sign up.

### PR DESCRIPTION
**Pull request by gr455**
Fixes #443
Screenshot from 2020-02-16 00-45-39

Make sure these boxes are checked before your pull request is ready to be reviewed and merged. Thanks!

* [x] tests pass -- `rake test`
* [x] code is in uniquely-named feature branch, and has been rebased on top of latest master (especially if you've been asked to make additional changes)
* [x] pull request are descriptively named
* [x] if possible, multiple commits squashed if they're smaller changes
* [x] reviewed/confirmed/tested by another contributor or maintainer

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/wiki/contributing-to-public-lab-software

Thanks!

### CODE REVIEW

**Comment by gr455** [comment]
Whoops! looks like a version error is causing Travis to fail. Help needed

**Comment by gr455** [comment]
@Uzay-G I did the necessary but why is Travis failing? Can you help me with that

**Comment by gr455** [comment]
> Why did you change the `shema.rb` file here? You only need to edit the button. Can you remove those diffs?
> Thanks!

I made the necessary changes but I don't recall changing schema.rb, how did it get changed?

**Review by jywarren — APPROVED** [review]

**Comment by jywarren** [comment]
Very very late, please forgive us! But rebased and should be able to merge asap!

**Comment by gr455** [comment]
> Very very late, please forgive us! But rebased and should be able to merge asap!

Haha. No problem @jywarren. Glad to see SW after a long time :)

**Comment by jywarren** [comment]
Hooray!!!! Thank you!!!!!!

**Comment by jywarren** [comment]
Lots up updates/improvements merged, and lots of Dependabot work!

**Pull request merged**
