### PR TITLE
Bug/test config error

### PR DESCRIPTION
**Pull request by jrslagle**
This fix makes bundle exec rake pass all tests on new installs. The failing test used to be this:

[4/6] ExceptionsTest#test_GET_/sets/show/# = 0.10 s    
  1) Error:
ExceptionsTest#test_GET_/sets/show/#:
ActionView::Template::Error: undefined method `[]' for nil:NilClass
    /home/[path]/spectral-workbench/app/views/sets/show.html.erb:108:in `_app_views_sets_show_html_erb__548404879__574367738'

Putting this in config/config.yml.example as well as config/config.yml will make it so new installs won't see this error.

test:
  local: true

### CODE REVIEW

**Comment by jywarren** [comment]
Super. If you could rebase this too it'd be great. (Trying to stick to our [contributor guidelines](http://publiclab.org/wiki/contributing-to-public-lab-software) :-) ) Thanks so much!

**Comment by jywarren** [comment]
I've rebased and merged this. Thanks!

**Comment by jrslagle** [comment]
Thanks for rebasing for me. I was away for the weekend.

**Comment by jywarren** [comment]
:) happy to! thanks again for your commit.

**Pull request closed without merging**
