### PR TITLE
New capture check on unstable

### PR DESCRIPTION
**Pull request by waridrox**
Make sure these boxes are checked before your pull request is ready to be reviewed and merged. Thanks!

* [ ] tests pass -- `rake test`
* [ ] code is in uniquely-named feature branch, and has been rebased on top of latest master (especially if you've been asked to make additional changes)
* [ ] pull request are descriptively named
* [ ] if possible, multiple commits squashed if they're smaller changes
* [ ] reviewed/confirmed/tested by another contributor or maintainer

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/wiki/contributing-to-public-lab-software

Thanks!

### CODE REVIEW

**Comment by waridrox** [comment]
Hi @jywarren @pydevsg could you pls approve the merge...It seems that I don't have merge rights to push it to `unstable` 😅. I just wanted to know if the rear camera feed works on mobile devices.  

Thanks

**Comment by pydevsg** [comment]
Hi, @waridrox the tests are failing can you please check them once?
Also, please checkout the boxes and will review then.
Lately, can you also put a GIF/image on the updated changes?
Thanks :)

**Comment by waridrox** [comment]
I would be pushing more changes incorporating responsive layouts and since the gitpod already builds the app. I think there's no need to merge the PR. Thanks!!!

**Comment by jywarren** [comment]
OK - just keep in mind @waridrox that we really want to see regular well-separated or compartmentalized PRs that are merge-able. Please do your best to plan and execute your work in chunks that can be individually and separately merged. Thank you!!

**Comment by jywarren** [comment]
Check out https://publiclab.org/notes/warren/01-18-2018/software-outreach-modularity-is-great-for-collaboration for some thoughts on modularity of this kind! 🎉

**Comment by waridrox** [comment]
Oh no...I'm really sorry about that!!! It's just that all the things seem so inter-connected that this idea almost slipped my mind. @jywarren should I then close #660 to pick out the commits in their own feature branches ?

**Comment by RuthNjeri** [comment]
@waridrox I think the idea you have shared to build out #660 's commits into branches makes sense if each commit is a significant change. You can choose to close it once you have finished breaking it down.

**Comment by jywarren** [comment]
Agreed with @RuthNjeri - yes, let's do that - that way we can resolve them one by one as well. Thanks!

**Pull request closed without merging**
