### PR TITLE
Add index to tag_id field in snapshots table to help performance.

### PR DESCRIPTION
**Pull request by icarito**
This small patch was pushed to production this morning.

### CODE REVIEW

**Comment by jywarren** [comment]
Ah, but is not merged into master? If it works, can you confirm and we can merge here?

**Comment by icarito** [comment]
It is a bit early to tell but shields appear to be holding...

**Comment by jywarren** [comment]
super, merged. saw your other comment confirming in https://github.com/publiclab/spectral-workbench/issues/359#issuecomment-212998017

**Comment by icarito** [comment]
Yes sorry for posting twice out of enthusiasm :-)

**Comment by jywarren** [comment]
np, very glad to see it stabilized

**Pull request merged**
