### PR TITLE
Container settings and testing configuration

### PR DESCRIPTION
**Pull request by icarito**
This pull request adds:
- Dockerfile for making a container.
- docker-compose.yml for testing deployment configuration
- .travis.yml for testing configuration

Currently setup to run jasmine:ci tests.

Make sure these boxes are checked before your pull request is ready to be reviewed and merged. Thanks!

* [ ] tests pass -- `rake test`
  Actually I it appears like `paginate` method does not support `order` parameter anymore. Can you tell me what Gem this is? Auto running tests should help.

* [ ] code is in uniquely-named feature branch, and has been rebased on top of latest master (especially if you've been asked to make additional changes)
  Learning feature branches...

* [X] pull request are descriptively named
* [ ] if possible, multiple commits squashed if they're smaller changes
  Can be done...
* [ ] reviewed/confirmed/tested by another contributor or maintainer

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/wiki/contributing-to-public-lab-software

Thanks!

### CODE REVIEW

**Comment by icarito** [comment]
Here's the ci for my fork: https://travis-ci.org/icarito/spectral-workbench/builds

**Comment by jywarren** [comment]
Oh cool! It says failing, though; is that related to the test setup? They're passing on my development setup.

**Comment by icarito** [comment]
We are finding issues already! Great start!
I wonder about it too. Does the empty DB have any spectra? Currently we do `rake db:setup` and `'rake db:seed` - is the seed db enough for this test to pass?

From the test code it appears to be testing for a visual that would only appear in a table populated with (at least 6) spectra:

```
  it("should highlight table row when hovering over graph line ", function() {
*/

    // this syntax is to trigger an SVG mouseover using D3:
    d3.select('g.nv-scatterWrap g#spectrum-hover-1')[0][0].dispatchEvent(new MouseEvent('mouseover'));
  
    expect($('tr.spectrum-1').hasClass('highlight')).toBe(true);
    expect($('tr.spectrum-2').hasClass('highlight')).toBe(false);  
    expect($('tr.spectrum-4').hasClass('highlight')).toBe(false);
    expect($('tr.spectrum-6').hasClass('highlight')).toBe(false);

  });
```

Here's the test output:
( locally the same as https://travis-ci.org/icarito/spectral-workbench )
```
icarito@tycho:/srv/ci-spectralworkbench/spectralworkbench$ docker-compose run web bundle exec rake jasmine:ci  
[2016-06-11 07:15:26] INFO  WEBrick 1.3.1  
[2016-06-11 07:15:26] INFO  ruby 2.1.2 (2014-05-08) [x86_64-linux]  
[2016-06-11 07:15:26] INFO  WEBrick::HTTPServer#start: pid=1 port=58489  
Waiting for jasmine server on 58489...  
jasmine server started  
Phantomjs does not appear to be installed in /root/.phantomjs/2.1.1/x86_64-linux/bin/phantomjs, installing!  
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current  
                                 Dload  Upload   Total   Spent    Left  Speed  
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0  
100 22.3M  100 22.3M    0     0  19.5M      0  0:00:01  0:00:01 --:--:-- 84.6M  
  
Successfully installed phantomjs. Yay!  
Removed temporarily downloaded files.  
........................*.........*.........**..******F...........*..................*.....  
Failures:   
          Set should initialize line styling and table rows properly  
  
          TypeError: MouseEventConstructor is not a constructor (evaluating 'new MouseEvent('mouseover')') in http://localhost:58489/__spec__/set_spec.js (line 104)  
          http://localhost:58489/__spec__/set_spec.js:104:88  
attemptSync@http://localhost:58489/__jasmine__/jasmine.js:1886:28  
run@http://localhost:58489/__jasmine__/jasmine.js:1874:20  
execute@http://localhost:58489/__jasmine__/jasmine.js:1859:13  
queueRunnerFactory@http://localhost:58489/__jasmine__/jasmine.js:697:42  
execute@http://localhost:58489/__jasmine__/jasmine.js:359:28  
fn@http://localhost:58489/__jasmine__/jasmine.js:2479:44  
  
Pending:  
        Graph makes imgContainer match width of graph bounds  
          Temporarily disabled with xit  
  
        Graph makes imgContainer match width of graph bounds after a range is set  
          Temporarily disabled with xit  
  
        Operation properly parses crossSection operation  
          Temporarily disabled with xit  
  
        Operation crossSection parse() callback is called  
          Temporarily disabled with xit  
  
        Operation properly parses linearCalibration operation  
          Temporarily disabled with xit  
  
        Operation properly clears after destroying crossSection operation  
          Temporarily disabled with xit  
  
        Reversal flips image horizontally in CSS if linearCalibrated with x1 > x2  
          Temporarily disabled with xit  
  
        Reversal un-reverses image horizontally in CSS if linearCalibrated with x1 > x2 is removed  
          Temporarily disabled with xit  
  
        Reversal detects if an image doesn't match its graph before other spectra run  
          Temporarily disabled with xit  
  
        Reversal displays calibration image backwards and reverses start/end when calibrating, if B2 > G2  
          Temporarily disabled with xit  
  
        Spectrum imgToJSON() extracts JSON data from an image  
          Temporarily disabled with xit  
  
        UI should replace spaces in tags with dashes  
          Temporarily disabled with xit  
  
91 specs, 1 failure, 12 pending specs  
[2016-06-11 07:15:43] INFO  going to shutdown ...  
[2016-06-11 07:15:43] INFO  WEBrick::HTTPServer#start done.  
```

**Comment by jywarren** [comment]
Ah - two things, first those are client side tests, while the server side
tests (which use the database) are run with 'rake test' -- second, I think
I resolved that bug in the latest master, with a commit about a week ago.
Can you check that youre running against the latest master?

It's possible I didn't merge that change yet but I think I did.

**Comment by icarito** [comment]
Yes my fork is in sync with latest master branch.

Talking about server-side tests, those are failing too:
```
SetsControllerTest#test_should_get_index:
ArgumentError: unsupported parameters: :order
    /usr/local/lib/ruby/gems/2.1.0/gems/will_paginate-3.1.0/lib/will_paginate/active_record.rb:157:in `paginate'
    /app/app/controllers/sets_controller.rb:8:in `index'
```

**Comment by jywarren** [comment]
Ok, so what is the next step, to set up CI for publiclab master branch and
then work on code/gens until it passes, or should I do that in my own fork
first?

Thanks, Sebastian!

**Comment by icarito** [comment]
I suppose they are independent of each other so it's up to you.

I'll add `rake test` to travis configuration
I don't think it's necessary to wait for tests to pass to start integrating. Travis-ci wants me to have admin repo rights in order to setup webhooks, or you can tell travis about [publiclab/spectral-workbench](https://github.com/publiclab/spectral-workbench) from your user so it will set up hooks automatically.

**Comment by jywarren** [comment]
great, i gave you admin rights. I'll add this to my to-do list.

**Comment by icarito** [comment]
Creating new pull request with improvements from named branch

**Pull request closed without merging**
