### PR TITLE
Routes re-factoring and cleaning

### PR DESCRIPTION
**Pull request by vpowerrc**

### CODE REVIEW

**Comment by jywarren** [comment]
Wow, so fast! Thanks, i'll test this now.

**Comment by jywarren** [comment]
First off, I notice the `/analyze/spectrum/#` legacy paths are broken, but I can fix that.

**Comment by vpowerrc** [comment]
Yes. I changed them few days back. That time I didn't know that we have to preserve them. 
Great, thank you :)

**Comment by jywarren** [comment]
I also wonder about `spectrums` since correct english pluralization is `spectra` -- Rails has some custom pluralization code, maybe we can use that to fix it?

**Comment by btbonval** [comment]
@jywarren Actually the correct English pluralization is spectrums depending upon whom you ask. More and more frequently, English is being allowed to transliterate and then use its own grammar, rather than using the rules of other languages leading to pluralization like spectra.

**Comment by jywarren** [comment]
haha nice bryan, so maybe we don't have to worry. Can we point to a dictionary entry in comments?

**Comment by jywarren** [comment]
https://4loc.wordpress.com/2009/04/09/inflector-rails-pluralization/

**Comment by btbonval** [comment]
First found on wikipedia, with a link to this:
http://dictionary.reference.com/browse/spectrum
"noun, plural spectra  [spek-truh] (Show IPA), spectrums."

**Comment by btbonval** [comment]
Using Latin and Greek pluralizations and other declensions was an elite thing to do to separate the well bred and well educated from the unwashed masses. Terms of venery (gaggle of geese, murder of crows) were likewise used to determine whether you were speaking with someone high class or a mere peon.

Thanks to internationalization, pidgin English is very condensed and has logical rules. A decent amount of pidgin English is making its way into normal colloquial English.

Fact is English has no standards body, so there is no such thing as standard English.

**Comment by jywarren** [comment]
Nice ref. Bryan - in keeping with anti-jargon PL ethos! Convinced. 

So, I'm just hooking up legacy routes and double checking. We should write tests for our legacy routes! Ug. But almost ready to merge.

**Comment by jywarren** [comment]
Super duper, thanks Vidruanga!

**Comment by btbonval** [comment]
Today's English fun fact: octopi is considered acceptable in English by convention, but it is wrong from just about any other angle you could look at it from.

Octopus is Greek, but it sounds Latin. People use the Latin pluralization octopi instead of the Greek pluralization octopodes.

The proper English pluralization to avoid this mixup? Add -s, like always. Octopuses ... or is it octopusses? Darnit. ;)

**Comment by vpowerrc** [comment]
Cool!

**Pull request merged**
