### PR TITLE
Routes re-factoring 

### PR DESCRIPTION
**Pull request by vpowerrc**

### CODE REVIEW

**Comment by jywarren** [comment]
Hi, Viduranga - I'm merging in some smaller changes, but tell me when you're going to rebase and I can stop for a while so you have a window of opportunity to complete the rebase and submit it.

**Comment by jywarren** [comment]
It looks like we were discussing this in #91 instead of here; moving discussion here. Viduranga, would you like me to try rebasing this?

**Comment by vpowerrc** [comment]
Jeff,
I rebased successfully. 
Here's the new PR https://github.com/publiclab/spectral-workbench/pull/101

**Comment by jywarren** [comment]
merged in #102

**Pull request closed without merging**
