### PR TITLE
Includes Simplecov and codecov

### LINKED ISSUE #500: Configure simplecov to get test coverage
**Please describe the desired behavior.**
Describe the solution you'd like.

Have Simplecov tool to get the percentage of test coverage.

### PR DESCRIPTION
**Pull request by alaxalves**
Fixes #500 and #507 
Make sure these boxes are checked before your pull request is ready to be reviewed and merged. Thanks!

* [x] tests pass -- `rake test`
* [x] code is in uniquely-named feature branch, and has been rebased on top of latest master (especially if you've been asked to make additional changes)
* [x] pull request are descriptively named
* [x] if possible, multiple commits squashed if they're smaller changes
* [ ] reviewed/confirmed/tested by another contributor or maintainer

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/wiki/contributing-to-public-lab-software

Thanks!

### CODE REVIEW

**Comment by alaxalves** [comment]
Maybe include this steps also ? https://codecov.io/gh/publiclab/spectral-workbench

**Comment by cesswairimu** [comment]
Great @alaxalves...do you know a way to exclude codecov on /views folders to avoid the challenges we faced on mapknitter?..No worries if not we can still get this merged and investigate later..thanks

**Comment by alaxalves** [comment]
> Great @alaxalves  ...do you know a way to exclude codecov on /views folders to avoid the challenges we faced on mapknitter?..No worries if not we can still get this merged and investigate later..thanks

@cesswairimu I investigated this Codecov thing and could not find anything relevant. Let's get this merged and I'll open up an issue so we can track this. What do you think?

**Comment by cesswairimu** [comment]
sounds good

**Comment by jywarren** [comment]
Very nice! Thank you!!!!

**Pull request merged**
