### PR TITLE
Roles fetched from plots2

### PR DESCRIPTION
**Pull request by SidharthBansal**
Fixes https://github.com/publiclab/mapknitter/issues/369
Make sure these boxes are checked before your pull request is ready to be reviewed and merged. Thanks!

* [ ] tests pass -- `rake test`
* [ ] code is in uniquely-named feature branch, and has been rebased on top of latest master (especially if you've been asked to make additional changes)
* [ ] pull request are descriptively named
* [ ] if possible, multiple commits squashed if they're smaller changes
* [ ] reviewed/confirmed/tested by another contributor or maintainer

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/wiki/contributing-to-public-lab-software

Thanks!

### CODE REVIEW

**Comment by jywarren** [comment]
Hmm:

```

W: There is no public key available for the following key IDs:
9D6D8F6BC857C906
W: There is no public key available for the following key IDs:
7638D0442B90D010
W: Failed to fetch http://http.debian.net/debian/dists/jessie-updates/InRelease  Unable to find expected entry 'main/binary-amd64/Packages' in Release file (Wrong sources.list entry or malformed file)
E: Some index files failed to download. They have been ignored, or old ones used instead.
ERROR: Service 'web' failed to build: The command '/bin/sh -c apt-get update -qq && apt-get install -y imagemagick ruby-rmagick libmagickwand-dev libmagick++-dev bundler libmysqlclient-dev ruby-rmagick libfreeimage3 libfreeimage-dev ruby-dev gdal-bin python-gdal curl libcurl4-openssl-dev libssl-dev zip nodejs-legacy npm' returned a non-zero code: 100
The command "docker-compose build" failed and exited with 1 during .
```

I think perhaps we need some help from @icarito on this?

**Comment by SidharthBansal** [comment]
It is worth noting that similar pr in MK (https://github.com/publiclab/mapknitter/commit/ef48de5544e5afb7bda6761179871f2540506bb1) doesn't have any such problem and this pr is related to https://github.com/publiclab/plots2/pull/5571
Yeah it will be great to have @icarito 's help. 
Thanks everyone.

**Comment by icarito** [comment]
Yes this seems to be failing on main branch on account of using an old container image / ruby version. I'll find a fix!

**Comment by SidharthBansal** [comment]
Thanks Sebastian.

**Comment by SidharthBansal** [comment]
Moved to #450

**Pull request closed without merging**
