### PR TITLE
Add tests for sets and spectrums controller

### PR DESCRIPTION
**Pull request by gr455**
Make sure these boxes are checked before your pull request is ready to be reviewed and merged. Thanks!

* [x] tests pass -- `rake test`
* [x] code is in uniquely-named feature branch, and has been rebased on top of latest master (especially if you've been asked to make additional changes)
* [x] pull request are descriptively named
* [x] if possible, multiple commits squashed if they're smaller changes
* [x] reviewed/confirmed/tested by another contributor or maintainer

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/wiki/contributing-to-public-lab-software

Thanks!

### CODE REVIEW

**Comment by gr455** [comment]
No travis check?

**Comment by gr455** [comment]
> No travis check?

Okay Travis passed https://travis-ci.org/github/publiclab/spectral-workbench/builds/665210749?utm_medium=notification&utm_source=github_status . Not sure why it didn't show up here

**Comment by cesswairimu** [comment]
Rebasing with main to see if travis is triggered

**Comment by jywarren** [comment]
Awesome, thank you!

**Pull request merged**
