### PR TITLE
Camera switching dropdown element addition to /v2

### PR DESCRIPTION
**Pull request by waridrox**
This PR aims to achieve the following -

- Using adapterjs as a library instead of the CDN script
- Updating some styles for the interface
- Adding a dropdown element for the new interface at /v2

Make sure these boxes are checked before your pull request is ready to be reviewed and merged. Thanks!

* [ ] tests pass -- `rake test`
* [ ] code is in uniquely-named feature branch, and has been rebased on top of latest master (especially if you've been asked to make additional changes)
* [ ] pull request are descriptively named
* [ ] if possible, multiple commits squashed if they're smaller changes
* [ ] reviewed/confirmed/tested by another contributor or maintainer

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/wiki/contributing-to-public-lab-software

Thanks!

### CODE REVIEW

**Review by jywarren — APPROVED** [review]
Looks great! How does this relate to [publiclab/spectral-workbench.js] Camera switching in a dropdown list (#247) though? Thanks!!!!

**Comment by waridrox** [comment]
Oh I'm not able to get the context of #247 😅, here's the integration in the distributable file - https://github.com/publiclab/spectral-workbench.js/pull/247

**Review by jywarren — APPROVED** [review]

**Comment by jywarren** [comment]
Aha, i just linked to the wrong one - publiclab/spectral-workbench.js#247 is correct. Thank you!

**Comment by jywarren** [comment]
Once conflicts are resolved this is good to go! Thanks!

**Pull request merged**
