### PR TITLE
Add "raw" according to Rails 3 rules to avoid html tags

### PR DESCRIPTION
**Pull request by shuchitgandhi**

### CODE REVIEW

**Comment by jywarren** [comment]
This is a fix for https://github.com/publiclab/spectral-workbench/issues/89 -- have you tested it and can confirm that before you saw `<p>` tags and now no longer?

**Comment by shuchitgandhi** [comment]
Yes, there are no <p> tags in any comment on my local server.

**Comment by shuchitgandhi** [comment]
Yes, there are no `<p>` tags in the comment section on my local server. I have tested it.

**Comment by jywarren** [comment]
OK I will test this today and try to accept it. Is it rebased on top of the
current master? Thanks!

**Comment by shuchitgandhi** [comment]
Yes.

On Tue, Mar 3, 2015 at 6:50 PM, Jeffrey Warren <notifications@github.com>
wrote:

> OK I will test this today and try to accept it. Is it rebased on top of the
> current master? Thanks!
>
> On Tue, Mar 3, 2015 at 1:34 AM, Shuchit Gandhi <notifications@github.com>
> wrote:
>
> > Yes, there are no <p> tags in the comment section on my local server. I
> > have tested it.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/publiclab/spectral-workbench/pull/96#issuecomment-76894531
> >
>
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/publiclab/spectral-workbench/pull/96#issuecomment-76943587>
> .
>



-- 
Cheers,
Shuchit Gandhi

**Comment by jywarren** [comment]
Thank you!

**Pull request merged**
