### PR TITLE
Remove extra search option

### PR DESCRIPTION
**Pull request by thesparks**
Fixes for https://github.com/publiclab/spectral-workbench.js/issues/54
It seems that @avsingh999 created an issue not here and other gci candidates didnt find which file to change 

* [ ] tests pass -- `rake test`
* [ ] code is in uniquely-named feature branch, and has been rebased on top of latest master (especially if you've been asked to make additional changes)
* [ ] pull request are descriptively named
* [ ] if possible, multiple commits squashed if they're smaller changes
* [ ] reviewed/confirmed/tested by another contributor or maintainer

deepin-screen-recorder_select area_20181109154422

### CODE REVIEW

**Comment by thesparks** [comment]
@jywarren, @SidharthBansal, please check

**Comment by jywarren** [comment]
Could you make it so that upon arriving on a search page, the top search input is already shown? I think you can do this in JavaScript!

Thank you!!!

**Comment by thesparks** [comment]
@jywarren, Sorry, I missclicked and made 4 commits. Done

**Comment by jywarren** [comment]
Perfect, thank you!

**Pull request merged**
