### PR TITLE
Initialize database before server side tests.

### PR DESCRIPTION
**Pull request by icarito**
Missed this in last pull request.

Make sure these boxes are checked before your pull request is ready to be reviewed and merged. Thanks!

* [ ] tests pass -- `rake test`
* [ ] code is in uniquely-named feature branch, and has been rebased on top of latest master (especially if you've been asked to make additional changes)
* [ ] pull request are descriptively named
* [ ] if possible, multiple commits squashed if they're smaller changes
* [ ] reviewed/confirmed/tested by another contributor or maintainer

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/wiki/contributing-to-public-lab-software

Thanks!

### CODE REVIEW

**Comment by jywarren** [comment]
Hmm, it says all checks have failed :-( -- can you take a look? Thanks!

**Comment by icarito** [comment]
Yes of course I'm on it modifying until all is green, I'll ping you, sorry.

**Comment by jywarren** [comment]
oh apologies -- i get email notifications, so i just responded. I'll wait
until i hear from you directly or in a @ mention, thanks!

**Comment by icarito** [comment]
Sorry for the confusion, tests passing now.

**Comment by jywarren** [comment]
ah that makes sense! semver to the rescue, i hope?

**Comment by icarito** [comment]
I'm not too familiar with Gemfile intricacies but here I patched it and it worked well again https://github.com/publiclab/spectral-workbench/pull/377

**Pull request merged**
