### PR TITLE
Brute force sample row auto detection

### PR DESCRIPTION
**Pull request by Sreyanth**
This is from last year's GSoC

### CODE REVIEW

**Comment by jywarren** [comment]
Oh, cool -- is this rebased on top of the latest head? I guess so if it's auto-merge-able. Sorry, it's been a while since I looked at this code -- how does it work again?

**Comment by Sreyanth** [comment]
The image in the canvas is captured at the time the function is called, and all the rows are tested to figure out a non-over-exposed highest intensity row, and it is automatically set as the sample row.

The user still has the option of manually selected any other row by clicking on the canvas.

**Comment by jywarren** [comment]
OK, this looks great! Can you remove the file "passenger.3001.pid" however? Thanks!

**Comment by Sreyanth** [comment]
Oops, updated the gitignore file but forgot to check this. Thanks!

**Comment by jywarren** [comment]
Thanks!!!

**Pull request merged**
