### PR TITLE
bumping spectral-workbench.js to v0.1.0 and dropping Jasmine tests

### PR DESCRIPTION
**Pull request by jywarren**
* [x] tests pass -- `rake test`
* [x] code is in uniquely-named feature branch, and has been rebased on top of latest master (especially if you've been asked to make additional changes)
* [x] pull request are descriptively named
* [x] if possible, multiple commits squashed if they're smaller changes
* [x] reviewed/confirmed/tested by another contributor or maintainer
* [x] manual testing

@icarito - I noticed the tests were a lot more verbose -- was there a debug flag set somewhere, or is it just my local env? 

This should be manually tested as well, as it integrates some major changes from [SpectralWorkbench.js](https://github.com/publiclab/spectral-workbench.js) v0.1.0

### CODE REVIEW

**Comment by icarito** [comment]
There's no debug setting set at all. Perhaps you've disabled warnings in your dev environment?

**Comment by jywarren** [comment]
Hmm, take a look - it's extremely verbose on Travis too:
https://travis-ci.org/publiclab/spectral-workbench/builds/139235241 -- what
do you think?

**Comment by icarito** [comment]
Okay I see what's going on. You and the testing environment is using a different environment setting: `config/environments` is where they are configured. One may disable warnings but ultimately I think they are a good thing to have for our code (but not dependencies). I'll look for an option to disable warnings for dependencies.

**Comment by jywarren** [comment]
Ah, ok, excellent, thanks! Btw with both swb repos using CI, today's
deployment was really smooth and excellent -- thanks!

**Comment by jywarren** [comment]
I found here some good guides on managing warnings:
http://stackoverflow.com/questions/5591509/suppress-ruby-warnings-when-running-specs
-- some are set in environment variables.

**Pull request merged**
