### PR TITLE
Routes re-factoring and cleaning

### PR DESCRIPTION
**Pull request by vpowerrc**
This is not yet ready for merging; just posting to stay coordinated.

### CODE REVIEW

**Comment by jywarren** [comment]
This pulled nicely into my asset-pipeline branch, thanks. Tests ran. I am merging into master and we should try it on a test server before pushing it to production. 

If we can build out more tests, the test server will not be necessary!

**Comment by vpowerrc** [comment]
Actually I'm not finished yet. I'm still updating.

**Comment by jywarren** [comment]
Sorry, I understood from your other comment () that you were done. Does this code not work? 

    redirect_to user_path(current_user.login)

Looks like it's fine; would you like to open a new pull request with your additional routes changes? 

Just a heads up -- next, I will be working on the dashboard markup and someone on the mailing list was going to work on the macro environment. I will probably move on to adding paginations for optimization, then probably improvements to the graphing setups.

**Comment by vpowerrc** [comment]
No, it works fine. But I'm refactoring more routes. 
Please check https://github.com/publiclab/spectral-workbench/pull/93

**Comment by jywarren** [comment]
Ah, ok, great, thanks.

**Comment by jywarren** [comment]
Ah, I noticed a bug -- the route `/profile/warren` does not work, with error:

`The action 'profile' could not be found for UsersController`

I'm going to fix this; I think your link generator code uses the route `/users/warren` but we want to preserve the old URL schema; I think we can override the default generated route. Will fix this today.

**Comment by vpowerrc** [comment]
Ohh, I intentionally removed it. I didn't keep old url pattern in any of the route changes I did, because it violates the REST principle and makes route file untidy.

**Comment by jywarren** [comment]
Ah, well we can't break legacy URLs because users will have linked to them.
We can redirect them to new URLs, however.

**Comment by vpowerrc** [comment]
Ah, okay. That only applies to GET requests ,right?

**Comment by jywarren** [comment]
Yes; the REST interface should be built in parallel, and we can def.
redirect any redundant legacy routes to it; some links and search engines
will update if we use a permanent redirect; see "redirection" here:
http://guides.rubyonrails.org/routing.html

**Comment by jywarren** [comment]
Sorry to revert your path changes -- but I used a new path helper, `profile_path` so your change from it being hard-coded is still preserved; it's just using a legacy route generator instead of `user_path` -- but `user_path` still exists.

**Comment by vpowerrc** [comment]
Okay no problem.
BTW now I'm ready to rebase my changes. To which branch should I rebase to?

**Comment by jywarren** [comment]
Pull in the latest master, then rebase on top of master. Great!

**Comment by vpowerrc** [comment]
Hmm I think something went wrong. Upon rebase most of my new commits went missing.

**Comment by jywarren** [comment]
you should always be able to recover an old commit state with `git rest
--hard <commit id>` -- try that, then follow the instructions on
http://publiclab.org/wiki/contributing-to-public-lab-software one by one

**Comment by jywarren** [comment]
erg `git reset` not `git rest`, sorry!

**Comment by jywarren** [comment]
And this time, probably make a backup branch of your features before trying
the git rebase!

**Comment by vpowerrc** [comment]
I was able to recover using "git rebase --abort" since rebase was not completed due to conflicts. I already have a copy on the remote. So no worries.

I followed the exact steps mentioned there. My previous rebase went well. That was with your asset-pipeline branch.

**Comment by jywarren** [comment]
Hmm. Are you in your feature branch when running `git rebase master` ?

**Comment by vpowerrc** [comment]
Yes of course. I did it couple of times now. Always end up with same results

**Comment by vpowerrc** [comment]
It seems, if I do "merge master" it works correctly.

**Comment by jywarren** [comment]
Hmm, merge master would put master on top of your feature branch, not the
other way around, and there should be no need to merge if rebasing works
correctly. How do you know your commits are missing? git log? Do you have a
remote branch I can clone to try it myself?

**Comment by vpowerrc** [comment]
Well, when I go to the text editor to fix conflicts, I noticed that my updated code is not there.

Yes, you can fetch routes-2 branch from my repo

**Comment by btbonval** [comment]
@jywarren It sounds like there is a complex merge conflict of some kind which rebase couldn't handle. merge can handle things rebase cannot.

Honestly, if you guys are sharing branches and pushing them back and forth to remote hosts like this, rebase is not a good idea.

You should never rebase a branch that has been pushed, although there are ways to handle it.

Merging will work just as well as rebase, but it makes the history ugly.

**Comment by jywarren** [comment]
He just pushed to a remote so that I can try the rebase myself. Not pushing back and forth to remote hosts -- just Github.com itself, for troubleshooting. I'm also happy with a merge, but @manleyjster has made a compelling case for rebasing, and I don't see why it shouldn't work. I think there's something else going on here if it's failing silently; if there were a conflict, it'd spit out an error.

**Comment by btbonval** [comment]
@jywarren He needed to `rebase --abort` in order to restore his git state. That generally means there was an error. Silent or not, it didn't work swimmingly ;)

**Comment by jywarren** [comment]
Hmm indeed -- what was the output of got rebase, Viduranga?

**Comment by vpowerrc** [comment]
git rebase master 
First, rewinding head to replay your work on top of it...
Applying: fixed issue with ajax loading icon
Applying: added raw before RDiscount
Applying: changed analyze/spetrum/:id action to spectrum/:id
Using index info to reconstruct a base tree...
M	app/controllers/capture_controller.rb
M	app/controllers/spectrums_controller.rb
M	app/views/analyze/_clone_results.html.erb
M	app/views/analyze/_commenting.html.erb
M	app/views/analyze/_compare_search.html.erb
M	app/views/analyze/spectrum.html.erb
M	app/views/match/_list_results.html.erb
M	app/views/match/_livesearch.html.erb
M	app/views/match/_match_results.html.erb
M	app/views/sets/_spectra.html.erb
M	app/views/sets/show.html.erb
M	app/views/spectrums/_list.html.erb
M	config/routes.rb
M	test/functional/spectrums_controller_test.rb
<stdin>:1541: trailing whitespace.
</div> 
<stdin>:1554: trailing whitespace.
</div> 
<stdin>:1616: space before tab in indent.
    	f.id = "clone<%= spectrum.id %>form"
<stdin>:1617: space before tab in indent.
    	var i = document.createElement('input');
<stdin>:1618: space before tab in indent.
    	i.name = "authenticity_token"
warning: squelched 6 whitespace errors
warning: 11 lines add whitespace errors.
Falling back to patching base and 3-way merge...
Auto-merging test/functional/spectrums_controller_test.rb
Auto-merging config/routes.rb
CONFLICT (content): Merge conflict in config/routes.rb
Auto-merging app/views/spectrums/show/_set.html.erb
Auto-merging app/views/spectrums/show/_macros.html.erb
Auto-merging app/views/spectrums/show/_compare.html.erb
Auto-merging app/views/spectrums/show/_clone.html.erb
Auto-merging app/views/spectrums/show.html.erb
Auto-merging app/views/spectrums/_list.html.erb
CONFLICT (content): Merge conflict in app/views/spectrums/_list.html.erb
Auto-merging app/views/sets/show.html.erb
Auto-merging app/views/sets/_spectra.html.erb
Auto-merging app/views/match/_match_results.html.erb
CONFLICT (content): Merge conflict in app/views/match/_match_results.html.erb
Auto-merging app/views/match/_livesearch.html.erb
CONFLICT (content): Merge conflict in app/views/match/_livesearch.html.erb
Auto-merging app/views/match/_list_results.html.erb
CONFLICT (content): Merge conflict in app/views/match/_list_results.html.erb
CONFLICT (modify/delete): app/views/analyze/_commenting.html.erb deleted in changed analyze/spetrum/:id action to spectrum/:id and modified in HEAD. Version HEAD of app/views/analyze/_commenting.html.erb left in tree.
Auto-merging app/controllers/spectrums_controller.rb
CONFLICT (content): Merge conflict in app/controllers/spectrums_controller.rb
Auto-merging app/controllers/capture_controller.rb
Removing app/controllers/analyze_controller.rb
Failed to merge in the changes.
Patch failed at 0003 changed analyze/spetrum/:id action to spectrum/:id
The copy of the patch that failed is found in:
   /home/viduranga/Desktop/gsoc/publiclab/spectral-workbench/.git/rebase-apply/patch

When you have resolved this problem, run "git rebase --continue".
If you prefer to skip this patch, run "git rebase --skip" instead.
To check out the original branch and stop rebasing, run "git rebase --abort".

**Comment by btbonval** [comment]
7 conflicts. Each file with a conflict needs to be resolved and committed
so that rebar can be continued.

Merge should have also raised the conflicts.

**Comment by vpowerrc** [comment]
@btbonval 
Yes, but it showed my updates. Rebase didn't show my updates.

**Comment by jywarren** [comment]
Hi, Viduranga - a couple things:

**Comment by jywarren** [comment]
ug sorry hit publish by accident; Hi, Viduranga - a couple things:

* due to a bad query, I've had to merge in one more change, so you'll have to `git pull` against publiclab's master again before trying another rebase.
* second, I believe that it will try to apply your changes sequentially (but this may not be true, i could be wrong or it could be only some modes of `git rebase`), so when it encounters a conflict, it stops, and you have to fix it and `git add` your fix, and run `git rebase --continue`. What I wonder is if perhaps it did your first commit only, and was waiting for you to fix the conflicts before continuing to play the rest of your commits on top. What do you think?

There is some guidance on git rebase available here: https://help.github.com/articles/resolving-merge-conflicts-after-a-git-rebase/

If that doesn't solve your problem, we can't figure it out otherwise, and you think you can git merge successfully, I'll accept that pull request.

**Comment by vpowerrc** [comment]
Jeff,
Yes that is exactly what has happened.

**Pull request merged**
