### PR TITLE
Rails 5.2 + Yarn + Tests + Static routing and more

### PR DESCRIPTION
**Pull request by alaxalves**
Make sure these boxes are checked before your pull request is ready to be reviewed and merged. Thanks!

* [x] tests pass -- `rake test`
* [x] code is in uniquely-named feature branch, and has been rebased on top of latest master (especially if you've been asked to make additional changes)
* [x] pull request are descriptively named
* [x] if possible, multiple commits squashed if they're smaller changes
* [ ] reviewed/confirmed/tested by another contributor or maintainer

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/wiki/contributing-to-public-lab-software

Thanks!

### CODE REVIEW

**Comment by jywarren** [comment]
What do you think, @alaxalves should I merge this? :tada

**Comment by alaxalves** [comment]
> What do you think, @alaxalves should I merge this?

Let's wait if others get the chance to review this. Maybe they find something weird

**Comment by jywarren** [comment]
🎉🎉🎉🎉

**Comment by alaxalves** [comment]
Hooooraaayyy !!!

**Comment by icarito** [comment]
hey https://github.com/publiclab/spectral-workbench/blame/main/script/start.sh#L19 this is wiping our database on deployment!

**Pull request merged**
