### PR TITLE
Updated .gitignore to remove node_modules folder

### LINKED ISSUE #659: Update .gitignore to ignore node_modules directory
Hi, this is a [first-timers-only issue](https://publiclab.github.io/community-toolbox/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### About the `.gitignore` file 
The `.gitignore` file in the project directory is created to ignore all the unwanted files which would otherwise be tracked by git (a version control system). Since the addition of `package.json` file in our codebase will create various files under the `node_modules` folder, we would like them to be ignored.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** the file [.gitignore](https://github.com/publiclab/spectral-workbench/blob/main/.gitignore) in the `spectral-workbench` repository (press the little pen Icon) and edit the line as shown below. 

[See this page](https://publiclab.github.io/community-toolbox/#r=all) for some help in taking your first steps!

Below is a "diff" showing in red (and a `-`) which lines to remove, and in green (and a `+`) which lines to add:
Add the following to the `.gitignore` file (without the `+` sign):

```diff
+ node_modules
```

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### 🤔❓ Questions?

Leave a comment below!

### Is someone else already working on this?

We encourage you to link to this issue by mentioning the issue # in your pull request, so we can see if someone's already started on it. **If someone seem stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://publiclab.github.io/community-toolbox/#r=all). Thanks!

(This issue was created by [First-Timers-Bot](https://github.com/hoodiehq/first-timers-bot).)

### PR DESCRIPTION
**Pull request by saraswathy-krish**
Fixes #659 Updated .gitignore to remove the node_modules folder

Make sure these boxes are checked before your pull request is ready to be reviewed and merged. Thanks!

* [ ] tests pass -- `rake test`
* [ ] code is in uniquely-named feature branch, and has been rebased on top of latest master (especially if you've been asked to make additional changes)
* [ ] pull request are descriptively named
* [ ] if possible, multiple commits squashed if they're smaller changes
* [ ] reviewed/confirmed/tested by another contributor or maintainer

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/wiki/contributing-to-public-lab-software

Thanks!

### CODE REVIEW

**Comment by waridrox** [comment]
Great work @saraswathy-krish!🥳 Just one more thing to note, often when making pull requests, we link the PR to the issue that the PR resolves/fixes. I encourage you to add one too. 
Just go over to the `Edit` option in the comment above and add this line 
**Fixes #issue_number** where issue_number is the number after the issue title and Github will automatically link the issue to the PR.
Thanks!

**Comment by saraswathy-krish** [comment]
Hi 

> Great work @saraswathy-krish!🥳 Just one more thing to note, often when making pull requests, we link the PR to the issue that the PR resolves/fixes. I encourage you to add one too.
> Just go over to the `Edit` option in the comment above and add this line
> **Fixes #issue_number** where issue_number is the number after the issue title and Github will automatically link the issue to the PR.
> Thanks!

Hi @waridrox ,I have made the suggested changes. Thanks for helping me out.

**Comment by waridrox** [comment]
Awesome @saraswathy-krish !!! ✨ @jywarren could you pls take a look at this. Meanwhile, if you're interested you could try solving other issues [here](https://github.com/publiclab/spectral-workbench/issues) or at [plots2 repo](https://github.com/publiclab/plots2/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22). Thanks!

**Review by waridrox — APPROVED** [review]

**Review by jywarren — APPROVED** [review]

**Comment by jywarren** [comment]
Awesome! Thank you!!!

**Pull request merged**
