### PR TITLE
Port Geocode tool back into new Capture interface,

### PR DESCRIPTION
**Pull request by Georjane**
Fixes #(update with issue number)

Make sure these boxes are checked before your pull request is ready to be reviewed and merged. Thanks!

* [x] tests pass -- `rake test`
* [x] code is in uniquely-named feature branch, and has been rebased on top of latest master (especially if you've been asked to make additional changes)
* [x] pull request are descriptively named
* [x] if possible, multiple commits squashed if they're smaller changes
* [ ] reviewed/confirmed/tested by another contributor or maintainer

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/wiki/contributing-to-public-lab-software

Thanks!

### CODE REVIEW

**Comment by Georjane** [comment]
Hi @jywarren @Tlazypanda 👋🏽 
I think i was able to read the `lat` and `lon` values using the geocode button.
But I am getting this error now
image

**Review by Tlazypanda — COMMENTED** [review]
Hey @Georjane after taking a quick look here's my guess - I see you have modified some id's in the code hmm... are we sure that supporting changes are there in the spectrums controller create method (the errors are invoked at lines 287 onwards) so maybe we can check the conditons in the controller and where it is failing my guess is the dataurl param is not getting saved now but pls log the values once to debug here, hope this makes sense cc @jywarren

**Comment by Georjane** [comment]
thanks very much @Tlazypanda 
The tests pass after I changed the `id` back to `dataurl`

**Comment by jywarren** [comment]
Oh fantastic, is this ready to merge then?

**Comment by jywarren** [comment]
So it looks like just need to re-add all the ` type="hidden"` lines! Then this can be merged 🎉

**Comment by Tlazypanda** [comment]
Hey @Georjane feel free to reach out if running into issue once you are done with the hidden part as @jywarren mentioned we are good to merge this!! and take the rest in a follow up pr :)

**Comment by Georjane** [comment]
hey @Tlazypanda @jywarren 
I was able to successfully create a spectrum now without having the error above
image

**Review by Tlazypanda — COMMENTED** [review]
Hey @Georjane @jywarren this looks good to merge :)

**Comment by jywarren** [comment]
Awesome!!!! 🎉

**Pull request merged**
