### PR TITLE
Add testing container

### PR DESCRIPTION
**Pull request by icarito**
This commit set adds:
  - Dockerfile for building a container for running spectral-workbench
  - docker-compose.yml for defining a testing environment
  - .travis.yml for continuous integration
  - some dependency issues
  - rake task comprising server and client side tests

Make sure these boxes are checked before your pull request is ready to be reviewed and merged. Thanks!

* [x] tests pass -- `rake test`
* [ ] tests pass -- `rake jasmine:ci` <br>
  Currently *one test fails*. Help is appreciated.
* [X] code is in uniquely-named feature branch, and has been rebased on top of latest master (especially if you've been asked to make additional changes)
* [X] pull request are descriptively named
* [X] if possible, multiple commits squashed if they're smaller changes
  Each is different and independent.
* [ ] reviewed/confirmed/tested by another contributor or maintainer
  To test locally:

```
cp config/database.yml.example config/database.yml
cp config/config.yml.example config/config.yml
docker-compose build
docker-compose run web bundle exec bower install --allow-root
docker-compose run web bundle exec rake assets:precompile --trace
docker-compose run web bundle exec rake test_all
```

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/wiki/contributing-to-public-lab-software

Thanks!

### CODE REVIEW

**Comment by icarito** [comment]
Just committed fix for not passing server-side test: reverting will-paginate Gem. Still jasmine not passing.

**Comment by icarito** [comment]
You can issue `docker-compose up` and then visit http://localhost:5000/ to see the testing instance. Not sure what the following failing test should be doing:
```
  it("should highlight table row when hovering over graph line ", function() {
*/  

    // this syntax is to trigger an SVG mouseover using D3:
    d3.select('g.nv-scatterWrap g#spectrum-hover-1')[0][0].dispatchEvent(new MouseEvent('mouseover'));

    expect($('tr.spectrum-1').hasClass('highlight')).toBe(true);
    expect($('tr.spectrum-2').hasClass('highlight')).toBe(false);
    expect($('tr.spectrum-4').hasClass('highlight')).toBe(false);
    expect($('tr.spectrum-6').hasClass('highlight')).toBe(false);

  });
```

**Comment by icarito** [comment]
https://travis-ci.org/publiclab/spectral-workbench/builds is ready and will trigger a build when a commit containing `.travis.yml` is merged

**Comment by jywarren** [comment]
I think i have a fix for the client side tests -- I had found and fixed this in SpectralWorkbench.js, which for better or worse duplicates these tests (since I pulled the javascript core out into its own library). You can see the fix here:

https://github.com/publiclab/spectral-workbench.js/blob/master/spec/javascripts/set_spec.js#L103-L117

However, I tried running this on my own machine and it can't seem to get it to use my local phantomjs binary; where can I set that?

**Comment by icarito** [comment]
Did you do `rake jasmine:ci` or `docker-compose run web bundle exec rake jasmine:ci`?

In the second case we're doing testing inside a Docker container where phantomjs isn't previously installed. We could preinstall phantomjs inside the container. To use your local phantomjs you could still use `rake jasmine:ci`.

**Comment by icarito** [comment]
Incidentally, Github just suggested advertised to me: 

```
Avoid bugs by automatically running your tests.
 
Learn more
Continuous integration can help catch bugs by running your tests automatically.
Merge your code with confidence using one of our continuous integration providers.
```

**Comment by jywarren** [comment]
I used `rake jasmine:ci` as I don't have a docker install locally. Did the test fix work, or should I make the changes and commit them? 

Yes, haha, well, hopefully we'll have that set up and it'll run when you submit a pull request, that'd be great. 

For the client side tests to be running, I believe phantomjs must already be available in the test environment you mentioned -- it got all the way to a JavaScript error, so it has to be. I was just interested in running it in the same manner locally as it'd be done remotely. Thanks!

**Comment by icarito** [comment]
On 14/06/16 11:33, Jeffrey Warren wrote:
>
> I used |rake jasmine:ci| as I don't have a docker install locally. Did
> the test fix work, or should I make the changes and commit them?
>
Yes I just tested, the test is fixed with your patch. I can commit a
rebased patch. Then will you merge?
>
> Yes, haha, well, hopefully we'll have that set up and it'll run when
> you submit a pull request, that'd be great.
>
> For the client side tests to be running, I believe phantomjs must
> already be available in the test environment you mentioned -- it got
> all the way to a JavaScript error, so it has to be. I was just
> interested in running it in the same manner locally as it'd be done
> remotely. Thanks!
>
Yes the testing container is throwaway although it can be sped up if
required
 by caching.

**Comment by jywarren** [comment]
Yes, happy to merge! Cool, thanks!

**Comment by icarito** [comment]
Confirmed tests passing now on travis ci! Please merge.

**Comment by jywarren** [comment]
Hmm, this seems to fail, though --

````
Index name 'index_users_on_login' on table 'users' already exists
/app/db/migrate/20120629103716_create_devices.rb:16:in `up'
ArgumentError: Index name 'index_users_on_login' on table 'users' already exists
/app/db/migrate/20120629103716_create_devices.rb:16:in `up'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
````

not sure why that's the case -- are you using `rake db:setup` or `rake db:create` ? The former would be the correct one.

**Comment by icarito** [comment]
Sorry that's my fault I did a last minute change because I found a
strange message about `rake test` not finding migrations up to date.

**Comment by jywarren** [comment]
No problem -- all passing now! Thanks, Sebastian, very exciting!

**Comment by icarito** [comment]
It appears to pass but it looks like it doesn't actually perform server tests now:
```
26.63s$ docker-compose run web bundle exec rake test_all
You have 37 pending migrations:
  20101121232659 CreateSpectrums
  20101122232339 AddPhotoPosition
  20101223225528 CreateVideos
  20110718153706 AddBaselineAndControlPoints
  20111108212348 CreateComments
  20120202021608 CreateSpectraSets
  20120202025658 AddSetComments
  20120204191448 AddLongerTextColumnLimit
  20120513232104 CreateUsers
  20120522212907 AddSpectrumsUserId
  20120525175257 AddRoles
  20120624214823 AddTagsAndLinkedSpectra
  20120626085916 AddSpectrumLatLon
  20120629103716 CreateDevices
  20120918115739 AddSpectrumsSampleRow
  20130205164725 CreateLikes
  20130214153953 AddUserEmailPrefs
  20130302223722 AddDeviceKey
  20130304165044 CreateMacros
  20130308184651 AddVideoRow
  20130820000000 ClosestMatch
  20130921134441 AddSpectrumReversal
  20150506174705 AddSpectrumsIndex
  20150624185446 AddAnonymousUser
  20150625194647 IndexSpectrumTitles
  20150715184613 AddSpectrumCalibrated
  20150715224222 CreateSetsSpectrumsJoinTable
  20150721195514 ChangeCommentAuthorToUser
  20150721201749 ConvertSpectrumDescriptionCalibrationToTag
  20150722210253 DeprecateSpectraSetAuthor
  20150723220742 DeduplicateCalibrationTagsAndUserIdsIntegers
  20150903140344 AddIndexLikesCount
  20150910150554 IndexSpectrumAuthor
  20150911020650 AddIndexTagName
  20151106174921 AddIndexTagSpectrumId
  20151202002150 CreateSnapshots
  20160421084510 AddIndexToSnapshots
Run `rake db:migrate` to update your database then try again.
[2016-06-14 17:54:21] INFO  WEBrick 1.3.1
```

**Comment by jywarren** [comment]
Hm, that's unfortunate. But I guess it's OK to continue adding fixes on top of this PR.

**Comment by jywarren** [comment]
Also, it's weird, but the travis test page says it failed, even though this PR log says it passed: https://travis-ci.org/publiclab/spectral-workbench

**Comment by icarito** [comment]
That's probably because I did another push after you merged and it triggered a re-run of the tests. I sent a new one now, waiting for test resuls.

**Pull request merged**
