### PR TITLE
Use the same version as available in container

### PR DESCRIPTION
**Pull request by icarito**
Otherwise stable won't build

Make sure these boxes are checked before your pull request is ready to be reviewed and merged. Thanks!

* [ ] tests pass -- `rake test`
* [ ] code is in uniquely-named feature branch, and has been rebased on top of latest master (especially if you've been asked to make additional changes)
* [ ] pull request are descriptively named
* [ ] if possible, multiple commits squashed if they're smaller changes
* [ ] reviewed/confirmed/tested by another contributor or maintainer

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/wiki/contributing-to-public-lab-software

Thanks!

### CODE REVIEW

**Comment by jywarren** [comment]
Noting link to @waridrox work at https://github.com/publiclab/spectral-workbench/pull/688 for Gitpod fix

**Comment by jywarren** [comment]
Hm, odd: 

```

Error:
HomeTest#test_Capture_Spectra_should_redirect:
Capybara::Ambiguous: Ambiguous match, found 3 elements matching visible css "a.btn.btn-large"
    test/system/home_test.rb:19:in `block in <class:HomeTest>'

bin/rails test test/system/home_test.rb:13
```

**Comment by jywarren** [comment]
i'll try restarting the system test... maybe it's intermittent

**Comment by waridrox** [comment]
> Hm, odd:
> 
> ```
> 
> Error:
> HomeTest#test_Capture_Spectra_should_redirect:
> Capybara::Ambiguous: Ambiguous match, found 3 elements matching visible css "a.btn.btn-large"
>     test/system/home_test.rb:19:in `block in <class:HomeTest>'
> 
> bin/rails test test/system/home_test.rb:13
> ```

This I believe is an intermittent test failure. I've seen this fail several times. Will update this soon...

**Comment by jywarren** [comment]
I believe i fixed the test in c7c9247b69f288a13d7961d8f82e0681808fcf6e and 84154ae5896ac58b116c99ff9b847cff31562a3b, will rebase this to check.

**Comment by jywarren** [comment]
Checking the test fixes in https://github.com/publiclab/spectral-workbench/pull/705 and also rebasing this.

**Comment by jywarren** [comment]
`ActionView::Template::Error: Asset `adapterjs/publish/adapter.min.js` was not declared to be precompiled in production.
Declare links to your assets in `app/assets/config/manifest.js`.`

**Comment by jywarren** [comment]
OK rebased and included a fix for the manifest.js file as recommended by tests.

**Comment by waridrox** [comment]
Sorry for the trouble but this should be the reference to the file since it is being referenced directly from the lib packages...
```
//= link adapterjs/publish/adapter.min.js
```

**Comment by jywarren** [comment]
I guess this looks OK? Merging now and we can see if we need to revive #688 later?

**Pull request merged**
